name: stylespree
favicon: null
layout_spectrum: 0.2548557948321104
typography_spectrum: 0.11031522671692073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17170f'
    - '#faf8e3'
    - '#c0d0d0'
    - '#6692af'
    - '#6d5637'
  brandStrength: 0.688702090177685
  lightness: 0.46652058558538556
  saturation: 0.673665470443666
  rhythmicContrast: 0.9243466530460864
purpose: []
